name: lsshelper
description: Flutter LSS Helper Daily Challenges app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.3.2+1
  cloud_firestore: ^0.14.1+3
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1
  flutter_absolute_path: ^1.0.6
  get: ^3.12.1
  image_cropper: ^1.3.1
  multi_image_picker: ^4.7.14
  scrollable_positioned_list: ^0.1.8
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
